### PR TITLE
tomp3 :v

### PR DESCRIPTION
**Pull request by idhamthoriqbot**
Jangan lupa pasang dulu ffmpeg:v

### CODE REVIEW

**Comment by lilnext01** [comment]
Error;


ReferenceError: content is not defined
    at WAConnection.handler (/storage/emulated/0/bot/unsaid/plugins/tomp3.js:14:61)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async WAConnection.handler (/storage/emulated/0/bot/unsaid/handler.js:249:13)

**Comment by BochilGaming** [comment]
Bisa dibuat masukin ke lib?

**Comment by lilnext01** [comment]
let { Presence, Mimetype } = require('@adiwajshing/baileys')
let ffmpeg = require('fluent-ffmpeg');
let fetch = require('node-fetch');
let ftype = require('file-type');
let fs = require('fs');
let { exec } = require('child_process');

let handler = async (m, { conn, text, args, usedPrefix, command }) => {

    m.reply('Convertendo, aguarde...')
   await conn.updatePresence(m.chat, Presence.composing)
	  let type = Object.keys(m.message)[0]
	  const content = JSON.stringify(m.message)
      let isMedia = (type === 'videoMessage')
      let isQuotedVideo = type === 'extendedTextMessage' && content.includes('videoMessage')
      if (!m.quoted) return conn.reply(m.chat, 'Responda à um vídeo!', m)
	  if (!isQuotedVideo) return m.reply('Apenas para Vídeo!')
	  let encmedia = JSON.parse(JSON.stringify(m).replace('quotedM', 'm')).message.extendedTextMessage.contextInfo
	     let media = await conn.downloadAndSaveMediaMessage(encmedia)
	     let ran = ('.mp3')
		     exec(`ffmpeg -i ${media} ${ran}`, (err) => {
					fs.unlinkSync(media)
					let buffer = fs.readFileSync(ran)
					conn.sendFile(m.chat, buffer, { mimetype: 'audio/mp3', quoted: m })
                    fs.unlinkSync(ran)
                    })
      m.reply('Pronto!')
}
handler.help = ['mp3 _<responda à um vídeo>_']
handler.tags = ['audio']
handler.command = /^tomp3|mp3$/i
handler.fail = null
handler.exp = 0
handler.limit = true

module.exports = handler

**Comment by lilnext01** [comment]
Bug fixed.

**Comment by BochilGaming** [comment]
> > Bisa dibuat masukin ke lib?
> 
> Lib apa?

Itu liat aja leveling

**Pull request merged**
