### PR TITLE
Fix sticker?

### PR DESCRIPTION
**Pull request by BochilGaming**
- [x] Fix conversation failed
- [x] Delete module nodemon
- [x] Test

### CODE REVIEW

**Comment by Fernazer** [comment]
lowdb added bree

**Comment by BochilGaming** [comment]
> lowdb added bree

Kapan kapan bree

**Comment by BochilGaming** [comment]
> > lowdb added bree
> 
> Kapan kapan bree #83

**Comment by zatu22** [comment]
TypeError: Cannot read property 'ffmpeg' of undefined at sticker /lib/sticker.js:172:20 at WAConnection.handler /plugins/sticker_en.js:20:24

**Comment by BochilGaming** [comment]
> TypeError: Cannot read property 'ffmpeg' of undefined at sticker /lib/sticker.js:172:20 at WAConnection.handler /plugins/sticker_en.js:20:24

Kalau pakek jangan setengah setengah, biar gk error :v

**Comment by zatu22** [comment]
I changed both, but I always get an error message on different bot versions

**Comment by BochilGaming** [comment]
> I changed both, but I always get an error message on different bot versions

my bot run perfectly

**Pull request merged**
